"""Allow duplicate gc_code across different zones

Revision ID: 8b5f1422b82d
Revises: 
Create Date: 2025-10-28 08:12:32.115808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b5f1422b82d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checker')
    op.drop_table('log')
    op.drop_table('geocache_zone')
    op.drop_table('owner')
    with op.batch_alter_table('geocache', schema=None) as batch_op:
        batch_op.alter_column('coordinates_raw',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('original_latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('original_longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_geocache_gc_code'))
        batch_op.create_index(batch_op.f('ix_geocache_gc_code'), ['gc_code'], unique=False)
        batch_op.create_unique_constraint('unique_gc_code_zone', ['gc_code', 'zone_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geocache', schema=None) as batch_op:
        batch_op.drop_constraint('unique_gc_code_zone', type_='unique')
        batch_op.drop_index(batch_op.f('ix_geocache_gc_code'))
        batch_op.create_index(batch_op.f('ix_geocache_gc_code'), ['gc_code'], unique=1)
        batch_op.alter_column('original_longitude',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('original_latitude',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('coordinates_raw',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.create_table('owner',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('geocache_zone',
    sa.Column('geocache_id', sa.INTEGER(), nullable=False),
    sa.Column('zone_id', sa.INTEGER(), nullable=False),
    sa.Column('added_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['geocache_id'], ['geocache.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.id'], ),
    sa.PrimaryKeyConstraint('geocache_id', 'zone_id')
    )
    op.create_table('log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('geocache_id', sa.INTEGER(), nullable=False),
    sa.Column('author_id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('log_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('favorite', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['owner.id'], ),
    sa.ForeignKeyConstraint(['geocache_id'], ['geocache.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checker',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('geocache_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('url', sa.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['geocache_id'], ['geocache.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
